### ISSUE TITLE
How to Serve Stream to Multiple Clients?

### ISSUE THREAD

**Issue by axwaxw** [caseymcj/raspberrypi_node_camera_web_streamer#2]
This project works very well with a single client.  Congratulations - it is very useful.

However, I do not believe that this pattern would be suitable for multiple clients (i.e. ,multiple, simultaneous requests).  Are you able to suggest an alternative pattern?  I had considered writing the frame to file and then writing from the file to ```res``` for each request, however, I have not been able to get this work.

Thanks

**Comment by caseymcj** [comment]
Hi Alex,

Thanks for reaching out! And I'm glad you found the project useful. You
make a good point, and I too have thought a bit about how to optimize it
for multiple connections, though I'm not sure I have a great answer yet.
But here are some of my thoughts:

   - The project currently does support multiple users viewing the same
   video stream at the same time. However...multicasting anything at 15 fps
   with each frame being ~25KB from a raspberry pi 3 is going to degrade
   quickly with 4+ clients. I'm not sure that there's any easy way to improve
   this without involving a significantly more powerful server (or a
   raspberry pi rack! :). Or if you cut the framerate
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L9>
   down to just a few per second, you could easily serve to a lot more clients.
   - An alternative to writing the frames to a shared file could be writing
   the frames to a shared global variable that all client requests could then
   refer to. Then have each inbound connection add a callback to a global list
   of listeners. Each time you save the frame to the global variable, iterate
   through the global list of listeners and execute those callbacks, and those
   could in turn write that single global frame variable to each of the open
   requests.
   - However, as it stands, I think this is already how
raspberry-pi-camera-native
   works <https://www.npmjs.com/package/raspberry-pi-camera-native/v/0.0.0>.
   With my project, currently each new connection
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L25>
   results in an event listener being added
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L64>
   to the shared "raspberryPiCamera" instance
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L16>
(we're
   not creating a new instance with each request, so there shouldn't be any
   added overhead beyond copying the frame to each connection stream). When a
   new image is ready from the camera
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L40>,
   that same frame is written to each connection
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L52>.
   I can't actually prove this exact behavior since I don't know for sure how
   raspberry-pi-camera-native is handling its event listeners, but I'd be
   surprised if it doesn't follow this convention. I think in practice this is
   about as efficient as writing the camera stream to a file or a global
   variable and then streaming from that shared data to clients... but again,
   I think a pi 3 is going to really struggle with more than just a few
   clients with any kind of stream from node.js...
   - I think you're exactly spot on with a better way to stream to multiple
   connections. You could use a lightweight raspberry-pi-camera-native node
   service to continuously write the frames to a .jpg file on a shared
   location. You could then have a more powerful computer serving those files
   up to client requests using my node_camera_web_streamer project (have it
   read from a file on a timed interval matching the frame rate rather than
   from the camera frame event
   <https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L40>
   on the pi). In theory this should not be very difficult to do. I think you
   said that you tried this, but you weren't able to get it to work. However,
   I think you're on the right track - it *should* work this way. If you
   used an AWS or Azure service to serve that file, there'd be no limit to the
   number of streams you could serve up from your pi!
   - Just remember that raspberry-pi-camera-native is passing along full,
   discrete images (in a variable) rather than sharing a stream. This is why
   my project is important - it takes those individual frames and creates a
   live stream to an HTML <img> tag. To adapt this to something else, you'll
   need to be sure to write those frames on an interval if you're reading them
   from a source other than the frame event listener on the
   raspberry-pi-camera-native.

Thanks again Alex for reaching out. I hope my thoughts above help. Best of
luck!!

Casey

**Comment by axwaxw** [comment]
Thanks Casey - I will persevere and let you know how I get on.  BTW I have also been experimenting with your methodology, but using [another camera package](https://github.com/launchcodedev/pi-camera-connect) (rather than raspberry-pi-camera-native).  I am not sure whether this will make a difference, since they both work in much the same way under the hood, but I'll let you know.

Thanks again.

**Comment by caseymcj** [comment]
OK, great! Good luck! If you find something that works better, go ahead and
send over a pull request if you'd like.
