### ISSUE TITLE
How to save one frame?

### ISSUE THREAD

**Issue by robMolloy** [caseymcj/raspberrypi_node_camera_web_streamer#3]
Really impressed with how well this project works, thanks!

Apologies, I have virtually 0 experience with image data.

Is there a way to retrieve frameData in videoStream.js in order to save an image or even better to save a video. 

frameData returns <Buffer ff d8 ff e1 00 de 45 78 69.... but I have no idea what to do with this.

Any help to point me in the right direction would be much appreciated.

**Comment by robMolloy** [comment]
I was unaware of buffers, sorry. Thanks again for this great project!

**Comment by caseymcj** [comment]
Hi Rob,

Yes, you're on the right track. Because javascript doesn't natively support
raw datatypes like binary or unencoded byte data, the Buffer class was
added in Nodejs to allow the underlying C++ to handle it correctly. That
said, you should be able to write that frameData using a buffer directly to
a file with a .jpg extension.

As far as capturing video, my project is based on another underlying
project called raspberry-pi-camera-native
<https://www.npmjs.com/package/raspberry-pi-camera-native>(my project
enables streaming from that project directly to a web page instead of just
to the filesystem). I don't think that library has a provision for video
capture. However, there's a low-level CLI tool with Raspbian called
"raspivid" that will do this for you. Here's a project (pi-camera)
<https://www.npmjs.com/package/pi-camera> that wraps some of that CLI that
should allow you to store video.

Best of luck!

Casey

**Comment by robMolloy** [comment]
Thanks a lot Casey.

I managed to solve my problem by editing your code to use an  "onEachFrame" callback as an addditional function within the acceptConnections setup. onEachFrame passes the frameDate, which can then be written into a file or manipulated in some other way by my own script. 

I don't know if you've considered (or want) this additional functionality but I'm happy to make a pull request if you'd like me to.

**Comment by robMolloy** [comment]
Sorry, one other thing, and I realise this is wrong issue thread.

If you follow the readme for the "Simple Example Project", in index.js it is important to change line 7; from;

`const videoStream = require('raspberrypi-node-camera-web-streamer');`
to
`const videoStream = require('./videoStream');`

Cheers again!

**Comment by caseymcj** [comment]
Hi Rob,

I know you made your own workaround for this, but I have added `videoStream.getLastFrame()` in the latest PR in case you're interested. This is based on your suggestion - good idea!

Also, I did correct a problem in the "Simple Example Project" as you mentioned - thank you for the hint. :)

Casey

**Comment by robMolloy** [comment]
Great to hear, I'm glad I could have a small impact on your excellent project!


-------- Original message --------
From: caseymcj ***@***.***>
Date: 16/05/2021 07:01 (GMT+00:00)
To: caseymcj/raspberrypi_node_camera_web_streamer ***@***.***>
Cc: Rob Molloy ***@***.***>, State change ***@***.***>
Subject: Re: [caseymcj/raspberrypi_node_camera_web_streamer] How to save one frame? (#3)


Hi Rob,

I know you made your own workaround for this, but I have added videoStream.getLastFrame() in the latest PR in case you're interested. This is based on your suggestion - good idea!

Also, I did correct a problem in the "Simple Example Project" as you mentioned - thank you for the hint. :)

Casey
