### ISSUE TITLE
Stream without Express?

### ISSUE THREAD

**Issue by PPosh98** [caseymcj/raspberrypi_node_camera_web_streamer#4]
Would it be possible to stream the footage without the express module? If so, I would appreciate if anyone could guide me on how to do this please. Thank you.

**Comment by caseymcj** [comment]
Hi PPosh98,

Great question! The main reason why Express is used is because it has an easy way of sharing static content from a public location. In the demo provided in this project, that's what's used to serve up the HTML page that then shows the camera stream.

In order to use something other than Express (thinking HTTP...?),[ just change videoStream.js](https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L2) to accept `HTTP` (or whatever serving library you choose) instead of `expressApp`. Then [change videoStream.js to serve up the stream using](https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/videoStream.js#L25) `HTTP` instead. You'll also need to make sure that references to `req` and `res` throughout the file are using the `HTTP` functions instead of Express functions.

Note that this is only going to make the _streamer_ work without Express, which is really all you need. I'm presuming that you already have a non-Express application that you're installing this into (why else would you want to avoid Express? ;), and so you don't need the demo page that's served up by [index.js](https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/blob/master/index.js). Otherwise, you'll need to convert that as well.

That said, here's my shameless plug: unless you have a specific reason _not_ to use Express, I would suggest considering Express, as it greatly simplifies configuring and serving up both static and dynamic content.

-caseymcj

**Comment by caseymcj** [comment]
Closing this issue for now due to inactivity.
